# Generated by Django 5.0.1 on 2024-02-02 06:05

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='servey',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='questions.survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.question'),
        ),
    ]
